### ISSUE TITLE
oci-env db reset leaves Pulp in a broken state

### ISSUE THREAD

**Issue by bmbouter** [pulp/oci_env#23]
At commit 2b0de81adf0d62027435900997b82dd8bb666857 if I run:

1. `oci-env compose up`
2. Check pulp is happy at the URL `http://localhost:5001/pulp/api/v3/` and it is
3. Try to reset the db with `oci-env db reset`
4. Check again Pulp is happy at `http://localhost:5001/pulp/api/v3/` and it isn't it gives a connection reset

What I expected from this command was to:
1. Stop the Pulp services
2. Delete the db
3. Recreate the db
4. Apply migrations
5. Start the services

I'm not sure (a) if that's what others expected or (b) how much of that is being done versus not done.

**Comment by newswangerd** [comment]
@bmbouter I think you might need to give it a moment to spin back up. I'm not 100% certain how compose restart works with podman-compose, but with docker it causes my running envionment to exit. If I run `oci-env db reset` and then `oci-env compose logs -f` I can see the db restarting and applying migrations.

**Comment by bmbouter** [comment]
When I run the `oci-env db reset` (I'm using podman), but it doesn't come back. What I see in the output from that command specifically is:

```
[2022-08-19 16:09:53 +0000] [486] [INFO] Handling signal: term
[2022-08-19 16:09:53 +0000] [487] [INFO] Handling signal: term
[2022-08-19 16:09:53 +0000] [573] [INFO] Worker exiting (pid: 573)
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Worker 485@8831e3fbef3e was requested to shut down.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Worker 489@8831e3fbef3e was requested to shut down.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Worker 489@8831e3fbef3e was shut down.
pulp [None]: pulpcore.tasking.pulpcore_worker:INFO: Worker 485@8831e3fbef3e was shut down.
[2022-08-19 16:09:53 +0000] [486] [INFO] Shutting down: Master
[2022-08-19 16:09:53 +0000] [561] [INFO] Worker exiting (pid: 561)
pulp [None]: asyncio:ERROR: Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<_heartbeat() running at /src/pulpcore/pulpcore/content/__init__.py:61> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fed697fd190>()]>>
[2022-08-19 16:09:54 +0000] [560] [INFO] Worker exiting (pid: 560)
pulp [None]: asyncio:ERROR: Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<_heartbeat() running at /src/pulpcore/pulpcore/content/__init__.py:61> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fed697fe100>()]>>
[2022-08-19 16:09:54 +0000] [487] [INFO] Shutting down: Master
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: supervisor died
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by bmbouter** [comment]
Wait a second, now it is working for me. Maybe I do need to wait a bit more!

**Comment by bmbouter** [comment]
Yeah this is working great for me. I think I wasn't waiting long enough. I'm closing since there is no problem here.
