### ISSUE TITLE
add a profile for telemetry dev env

### ISSUE THREAD

**Issue by dkliban** [pulp/oci_env#45]
The `telemetry` profile needs to spin up an additional container that serves `analytics.pulpproject.org` website. It should also modify the `/etc/hosts` file in the container running pulp to point `dev.analytics.pulpproject.org` to the container running that site.

**Comment by bmbouter** [comment]
Here are some docs I made on how to make a dev env manually. https://github.com/pulp/analytics.pulpproject.org/tree/dev
