### ISSUE TITLE
Add a scenario for the stream test runner

### ISSUE THREAD

**Issue by mdellweg** [pulp/oci_env#63]
This will start an sftp storage container and configure the corresponding storage class.

More information on how we configure it in the CI today:
https://github.com/pulp/pulpcore/blob/main/.github/workflows/scripts/install.sh#L86
https://github.com/pulp/pulpcore/blob/main/.ci/ansible/settings.py.j2#L29

**Comment by lubosmj** [comment]
The corresponding PR was closed because there is no longer interest in testing the unstable stream runner.
