### ISSUE TITLE
A mismatch between repositories' names and installed packages

### ISSUE THREAD

**Issue by lubosmj** [pulp/oci_env#92]
An issue occurs when a user runs tests for pulp-certguard within the environment. The environment should be capable of handling discrepancies between pulp-cerguard and pulp_certguard.

We decided not to rename the root name of the repository because we could not evaluate the impact of this change on sources that depend on pulp-certguard.

**Comment by lubosmj** [comment]
@mdellweg, was this issue addressed in https://github.com/pulp/oci_env/commit/f5f659384f432137b3bb2d33224562e3dc9e42f8?

**Comment by mdellweg** [comment]
I hope so. Can you verify please?
