### ISSUE TITLE
The modified file for pulpcore-api is outdated

### ISSUE THREAD

**Issue by mikedep333** [pulp/oci_env#95]
https://github.com/pulp/oci_env/blob/main/base/s6-rc-modifications/pulpcore-api/run

Does not include changes like PULP_API_WORKERS

In fact, we can probably just follow the advice in the file, and put the missing feature in pulp-oci-images instead.

**Comment by decko** [comment]
Closing since those changes got into through the https://github.com/pulp/oci_env/pull/98
